spring:
  application:
    name: auth-module

  datasource:
    url: jdbc:h2:mem:devTestDB
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  jwt:
    secret: 9F8a!1d$82kfj@c91v@83kld$38fa!0n
    access_expiration: 3600000
    refresh_expiration: 604800000

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG


server:
  port: 8080
